---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudian-cosi-driver
  labels:
    app.kubernetes.io/name: cloudian-cosi-driver
    app.kubernetes.io/part-of: cloudian-cosi-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudian-cosi-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudian-cosi-driver
    spec:
      containers:
        - name: cloudian-cosi-driver
          image: cloudian-cosi-driver:v0.0.0
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
          env:
          - name: S3_REGION
            value: {{ .Values.s3.region }}
          - name: S3_ENDPOINT
            value: {{ .Values.s3.s3Endpoint }}
          - name: IAM_ENDPOINT
            value: {{ .Values.s3.iamEndpoint }}
          - name: ADMIN_ENDPOINT
            value: {{ .Values.admin.endpoint }}
          - name: DISABLE_TLS_CERTIFICATE_CHECK
            value: "{{ .Values.disableTLSCertificateCheck }}"
          envFrom:
          - secretRef:
              name: cloudian-cosi-secret
        - name: objectstorage-driver-sidecar
          # Image tag v20241003-v0.1.0-58-g80979e8
          image: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar@sha256:42d190db77631505e2b0fd6dc7a3186e316a57da4e449566623d259f8f9b4ff8
          args: ["--debug", "-v", "100"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
      volumes:
        - name: socket
          emptyDir: {}
