---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role
  labels:
    app.kubernetes.io/name: cloudian-cosi-driver
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses", "bucketaccessclasses", "buckets/status", "bucketaccesses/status", "bucketclaims", "bucketclaims/status"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["secrets", "events"]
  verbs: ["get", "delete", "update", "create", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role-binding
  labels:
    app.kubernetes.io/name: cloudian-cosi-driver
subjects:
  - kind: ServiceAccount
    name: objectstorage-provisioner-sa
    namespace: default
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: objectstorage-provisioner-role
  apiGroup: rbac.authorization.k8s.io
