---
apiVersion: v1
kind: Secret
metadata:
  name: cloudian-cosi-secret
  labels:
    app.kubernetes.io/part-of: cloudian-cosi-driver
data:
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
  GROUP: {{ .Values.admin.group | b64enc }}
  ADMIN_USER: {{ .Values.admin.username | b64enc }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc }}
